# Generated by Django 6.0.2 on 2026-02-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
