# Generated by Django 6.0.2 on 2026-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_remove_messages_conversation_remove_messages_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
