# Generated by Django 6.0.2 on 2026-03-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/'),
        ),
    ]
