# Generated by Django 6.0.2 on 2026-03-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
